export const APP_TRANSLATIONS = {
  en: {
    appName: "BlindAssistance",
    common: {
      cancel: "Cancel",
      save: "Save",
      upload: "Upload",
      capture: "Capture",
      retake: "Retake",
      loading: "Loading...",
      yes: "Yes",
      no: "No",
    },
    navigation: {
      faces: "Faces",
      objects: "Objects",
      logs: "Logs",
      settings: "Settings",
    },
    home: {
      scanning: "Scanning...",
      detecting: "Detecting...",
      noObjects: "No objects detected",
      noDetections: "No faces or objects detected",
      unavailable: "Detection unavailable",
      cameraFallback: "Enable camera access to start detection",
      detectedSuffix: "detected",
      noObjectsSpeech: "No objects detected",
      noDetectionsSpeech: "No faces or objects detected",
      faceDetected: "Face detected",
      appTitle: "BlindAssistance",
    },
    settings: {
      title: "Settings",
      language: "Language",
      english: "English",
      arabic: "Arabic",
      voice: "Voice",
      speed: "Speed",
      voiceType: "Voice Type",
      male: "Male",
      testVoice: "Test Voice",
      detection: "Detection",
      faceDetection: "Face Detection",
      objectDetection: "Object Detection",
      accessibility: "Accessibility",
      highContrast: "High Contrast Mode",
      textSize: "Text Size",
      normal: "Normal",
      account: "Account",
      logout: "Log out",
      logoutTitle: "Log out",
      logoutMessage: "Are you sure you want to log out?",
      currentLanguage: "English",
      testVoicePhrase: "This is a voice test",
    },
    auth: {
      loginTitle: "Login",
      loginSubtitle: "Vision Aid",
      voiceGuide: "Tap for voice guide",
      email: "Email",
      password: "Password",
      login: "Login",
      createAccount: "Create Account",
      missingInfo: "Missing info",
      loginMissingBody: "Please enter your email and password.",
      loginFailed: "Login failed",
      loginFailedBody: "Unable to sign in.",
      registerTitle: "Register",
      registerVoiceGuide: "Voice guide",
      fullName: "Full Name",
      confirmPassword: "Confirm Password",
      register: "Register",
      alreadyHaveAccount: "Already have an account? Login",
      registerMissingBody: "Please fill in all fields.",
      passwordMismatchTitle: "Passwords do not match",
      passwordMismatchBody: "Please re-enter your password.",
      registrationFailed: "Registration failed",
      registrationFailedBody: "Unable to create account.",
    },
    addObject: {
      title: "Add Object",
      uploadOrCapture: "Upload or Capture",
      objectName: "Object Name",
      category: "Category (optional)",
      customObjects: "Custom Objects",
      permissionRequired: "Permission required",
      photoPermission: "Photo access is needed to upload an image.",
      missingInfo: "Missing info",
      missingNameBody: "Please provide an object name.",
      saveFailed: "Save failed",
      saveFailedBody: "Unable to save object.",
      deleteFailed: "Delete failed",
      deleteFailedBody: "Unable to delete.",
      uncategorized: "Uncategorized",
    },
    faces: {
      title: "Register Faces",
      cameraFallback: "Enable camera access",
      personName: "Person Name",
      savedFaces: "Saved Faces",
      permissionRequired: "Permission required",
      cameraPermission: "Camera access is needed to capture a face.",
      photoPermission: "Photo access is needed to upload an image.",
      captureFailed: "Capture failed",
      captureFailedBody: "Unable to capture the image. Please try again.",
      missingInfo: "Missing info",
      missingInfoBody: "Please provide a name and image.",
      saveFailed: "Save failed",
      saveFailedBody: "Unable to save face.",
      deleteFailed: "Delete failed",
      deleteFailedBody: "Unable to delete.",
      capture: "Capture",
      upload: "Upload",
      save: "Save",
      retake: "Retake",
    },
    logs: {
      title: "Detection Log",
      all: "All",
      faces: "Faces",
      objects: "Objects",
      empty: "No logs yet.",
    },
  },
  ar: {
    appName: "BlindAssistance",
    common: {
      cancel: "إلغاء",
      save: "حفظ",
      upload: "رفع",
      capture: "التقاط",
      retake: "إعادة التقاط",
      loading: "جارٍ التحميل...",
      yes: "نعم",
      no: "لا",
    },
    navigation: {
      faces: "الوجوه",
      objects: "الأجسام",
      logs: "السجل",
      settings: "الإعدادات",
    },
    home: {
      scanning: "جاري الفحص...",
      detecting: "جاري الاكتشاف...",
      noObjects: "لم يتم اكتشاف أي جسم",
      unavailable: "الاكتشاف غير متاح",
      cameraFallback: "فعّل إذن الكاميرا لبدء الاكتشاف",
      detectedSuffix: "تم اكتشافه",
      noObjectsSpeech: "لم يتم اكتشاف أي جسم",
      appTitle: "BlindAssistance",
    },
    settings: {
      title: "الإعدادات",
      language: "اللغة",
      english: "الإنجليزية",
      arabic: "العربية",
      voice: "الصوت",
      speed: "السرعة",
      voiceType: "نوع الصوت",
      male: "ذكر",
      testVoice: "اختبار الصوت",
      detection: "الاكتشاف",
      faceDetection: "اكتشاف الوجوه",
      objectDetection: "اكتشاف الأجسام",
      accessibility: "إمكانية الوصول",
      highContrast: "وضع التباين العالي",
      textSize: "حجم النص",
      normal: "عادي",
      account: "الحساب",
      logout: "تسجيل الخروج",
      logoutTitle: "تسجيل الخروج",
      logoutMessage: "هل تريد تسجيل الخروج؟",
      currentLanguage: "العربية",
      testVoicePhrase: "هذا اختبار للصوت",
    },
    auth: {
      loginTitle: "تسجيل الدخول",
      loginSubtitle: "مساعد الرؤية",
      voiceGuide: "اضغط للدليل الصوتي",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      login: "تسجيل الدخول",
      createAccount: "إنشاء حساب",
      missingInfo: "معلومات ناقصة",
      loginMissingBody: "يرجى إدخال البريد الإلكتروني وكلمة المرور.",
      loginFailed: "فشل تسجيل الدخول",
      loginFailedBody: "تعذر تسجيل الدخول.",
      registerTitle: "إنشاء حساب",
      registerVoiceGuide: "الدليل الصوتي",
      fullName: "الاسم الكامل",
      confirmPassword: "تأكيد كلمة المرور",
      register: "تسجيل",
      alreadyHaveAccount: "لديك حساب بالفعل؟ تسجيل الدخول",
      registerMissingBody: "يرجى تعبئة جميع الحقول.",
      passwordMismatchTitle: "كلمتا المرور غير متطابقتين",
      passwordMismatchBody: "يرجى إعادة إدخال كلمة المرور.",
      registrationFailed: "فشل التسجيل",
      registrationFailedBody: "تعذر إنشاء الحساب.",
    },
    addObject: {
      title: "إضافة جسم",
      uploadOrCapture: "رفع أو التقاط",
      objectName: "اسم الجسم",
      category: "الفئة (اختياري)",
      customObjects: "الأجسام المخصصة",
      permissionRequired: "إذن مطلوب",
      photoPermission: "تحتاج إلى إذن الصور لرفع صورة.",
      missingInfo: "معلومات ناقصة",
      missingNameBody: "يرجى إدخال اسم الجسم.",
      saveFailed: "فشل الحفظ",
      saveFailedBody: "تعذر حفظ الجسم.",
      deleteFailed: "فشل الحذف",
      deleteFailedBody: "تعذر حذف الجسم.",
      uncategorized: "غير مصنف",
    },
    faces: {
      title: "تسجيل الوجوه",
      cameraFallback: "فعّل إذن الكاميرا",
      personName: "اسم الشخص",
      savedFaces: "الوجوه المحفوظة",
      permissionRequired: "إذن مطلوب",
      cameraPermission: "تحتاج إلى إذن الكاميرا لالتقاط وجه.",
      photoPermission: "تحتاج إلى إذن الصور لرفع صورة.",
      captureFailed: "فشل الالتقاط",
      captureFailedBody: "تعذر التقاط الصورة. حاول مرة أخرى.",
      missingInfo: "معلومات ناقصة",
      missingInfoBody: "يرجى إدخال الاسم والصورة.",
      saveFailed: "فشل الحفظ",
      saveFailedBody: "تعذر حفظ الوجه.",
      deleteFailed: "فشل الحذف",
      deleteFailedBody: "تعذر حذف الوجه.",
      capture: "التقاط",
      upload: "رفع",
      save: "حفظ",
      retake: "إعادة التقاط",
    },
    logs: {
      title: "سجل الاكتشاف",
      all: "الكل",
      faces: "الوجوه",
      objects: "الأجسام",
      empty: "لا توجد سجلات بعد.",
    },
  },
};

export const DEFAULT_LANGUAGE = "en";

export const getTranslations = (language) =>
  APP_TRANSLATIONS[language] || APP_TRANSLATIONS[DEFAULT_LANGUAGE];

export const getLanguageConfig = (language) => {
  const normalized = language === "ar" ? "ar" : "en";
  return {
    code: normalized,
    label: normalized === "ar" ? "العربية" : "English",
    speechLocale: normalized === "ar" ? "ar-SA" : "en-US",
    direction: normalized === "ar" ? "rtl" : "ltr",
  };
};
